#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd shellinabox-2.14
set >/tmp/set-at-run
echo "Running shellinaboxd on port $PORT"
./shellinaboxd -p $PORT -s "/:$(id -u):$(id -g):$HOME:$SCRIPTPATH/login" --disable-ssl

